In [1]:
from ch2 import *
from scipy.linalg import *
import numpy as np

Amat = np.array([[3.,-1.,4.],
              [2.,0.,5.],
              [7.,2.,-2.]])

bmat = np.array([[ 6.0,  3.0,  7.0],
              [-4.0,  2.0, -5.0]])

A = Amat.copy()
b = bmat.copy()

np.linalg.solve(A,b.T)

array([[ 1.45283019, -1.45283019],
       [-1.56603774,  3.56603774],
       [ 0.01886792,  0.98113208]])

In [2]:
A = Amat.copy()
b = bmat.copy()

A = LUdecomp(A)
L = np.eye(3)
L[1,0] = A[1,0]
L[2,0] = A[2,0]
L[2,1] = A[2,1]
U = A - L + np.eye(3)

print(A,'\n',L,'\n',U)

[[  3.          -1.           4.        ]
 [  0.66666667   0.66666667   2.33333333]
 [  2.33333333   6.5        -26.5       ]] 
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [2.33333333 6.5        1.        ]] 
 [[  3.          -1.           4.        ]
 [  0.           0.66666667   2.33333333]
 [  0.           0.         -26.5       ]]


In [3]:
L@U

array([[ 3., -1.,  4.],
       [ 2.,  0.,  5.],
       [ 7.,  2., -2.]])

In [4]:
b = np.array([6.,3.,7.])
n = len(b)
y = np.zeros(n)
x = np.zeros(n)

for k in range(1,n):
    y[k] = (b[k] - np.dot(L[k,0:k],y[0:k]))/L[k,k]

for j in range(n-1,-1,-1):
    x[k] = (y[k] - np.dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
    
np.linalg.solve(Amat,b)
x

array([0.        , 0.        , 0.47169811])

In [ ]:
A = LUdecomp(A)
for i in range(len(b)):
    x = LUsolve(A,b[i,:])
    print('x', i+1,' = ', x)

In [5]:
AA = np.array([[1.,4.,1.],
              [1.,6.,-1.],
              [2.,-1.,2.]])
bb = np.array([7.,13.,5.])

A = AA.copy()
b = bb.copy()

L10 = A[1,0]/A[0,0]
A[1,:] = A[1,:] - L10*A[0,:]

L20 = A[2,0]/A[0,0]
A[2,:] = A[2,:] - L20*A[0,:]

L21 = A[2,1]/A[1,1]
A[2,:] = A[2,:] - L21*A[1,:]

L = np.eye(len(A))

L[1,0] = L10
L[2,0] = L20
L[2,1] = L21

U = A

L@U

array([[ 1.,  4.,  1.],
       [ 1.,  6., -1.],
       [ 2., -1.,  2.]])

In [6]:
n = len(b)
x = np.zeros(n)
y = np.zeros(n)

for k in range(0,n):
    y[k] = b[k] - np.dot(L[k,0:k],y[0:k])
for k in range(n-1,-1,-1):
    x[k] = (y[k] - np.dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
x

array([ 5.,  1., -2.])

In [7]:
np.linalg.solve(AA,bb)

array([ 5.,  1., -2.])

In [26]:
'''
  T            +m3*a3 = F2
 2T      +m2*a2       = F1
-3T+m1*a1             = 0
     -3a1+  2a2+   a3 = 0
'''
m1 = 20.
m2 = 40.
m3 = 10.
F1 = 10.
F2 = 10.


aa = np.array([[   1.,   0.,   0.,   m3],
               [  -3.,   m1,   0.,   0.],
               [   2.,   0.,   m2,   0.],
               [   0.,  -3.,   2.,   1.]])
f = np.array([F2,0,F1,0])

a = aa.copy()

L10 = a[1,0]/a[0,0]
a[1,:] = a[1,:] - L10*a[0,:]

L20 = a[2,0]/a[0,0]
a[2,:] = a[2,:] - L20*a[0,:]

L30 = a[3,0]/a[0,0]
a[3,:] = a[3,:] - L30*a[0,:]

L21 = a[2,1]/a[1,1]
a[2,:] = a[2,:] - L21*a[1,:]

L31 = a[3,1]/a[1,1]
a[3,:] = a[3,:] - L31*a[1,:]

L32 = a[3,2]/a[2,2]
a[3,:] = a[3,:] - L32*a[2,:]

L = np.eye(len(a))

L[1,0] = L10
L[2,0] = L20
L[3,0] = L30
L[2,1] = L21
L[3,1] = L31
L[3,2] = L32

U = a


n = len(f)
x = np.zeros(n)
y = np.zeros(n)

for k in range(0,n):
    y[k] = f[k] - np.dot(L[k,0:k],y[0:k])
for k in range(n-1,-1,-1):
    x[k] = (y[k] - np.dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
x

array([2.30769231, 0.34615385, 0.13461538, 0.76923077])