In [1]:
import numpy as np
import scipy as sp
from ch2 import *

In [2]:
A = np.array([[3.,-3.,3.],[-3.,5.,1.],[3.,1.,5.]])
b = np.array([9.,-7.,12.])

In [3]:
AA = A.copy()
bb = b.copy()
LU = LUdecomp(AA)   #LU decomposition
x = LUsolve(LU,bb)  #solve, forward, reverse
print('',x,'\n', np.linalg.solve(A,b))

 [3.5        0.66666667 0.16666667] 
 [3.5        0.66666667 0.16666667]


In [4]:
from scipy.linalg import lu
AA = A.copy()
bb = b.copy()
lu, piv = sp.linalg.lu_factor(AA)
x = sp.linalg.lu_solve((lu,piv),bb)
x

array([3.5       , 0.66666667, 0.16666667])

In [7]:
A = np.array([[4.,8.,20.],[8.,13.,16.],[20.,16.,-91.]], dtype = float )
b = np.array([24.,18.,-119.])

np.linalg.solve(A,b)

array([-3.,  2.,  1.])

In [6]:
AA = A.copy()
bb = b.copy()

LU = LUdecomp(AA)
x = LUsolve(LU,bb)
x

array([-3.,  2.,  1.])

In [14]:
#sparse matrix

np.random.rand(3,3)

array([[0.99659101, 0.30398067, 0.41286106],
       [0.86935131, 0.39686096, 0.22396001],
       [0.23949837, 0.33270421, 0.49668381]])

In [15]:
np.random.rand(3)

array([0.90991901, 0.10993195, 0.43298645])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [79]:
n=5
c = np.ones(n-1)
e = 2*np.ones(n-1)
d = 4*np.ones(n)
b = np.ones(n)

E = np.diag(e, k=+1)
C = np.diag(c, k=-1)
D = np.diag(d)

In [48]:
A = C+D+E
A

array([[4., 2., 0., 0., 0.],
       [1., 4., 2., 0., 0.],
       [0., 1., 4., 2., 0.],
       [0., 0., 1., 4., 2.],
       [0., 0., 0., 1., 4.]])

In [83]:
dp = d.copy()
cp = c.copy()

y = np.zeros(n)
x = np.zeros(n)


for k in range(1,n): # 1, 2, 3, ... , n-1
    lam = cp[k-1]/dp[k-1]
    dp[k] = dp[k] - lam*e[k-1]
    cp[k-1] = lam

y[0] = b[0]
for k in range(1,n):
    y[k] = b[k] - cp[k-1]*y[k-1]

x[n-1] = y[n-1]/dp[n-1]
for k in range(n-2,-1,-1):
    x[k] = (y[k] - e[k]*x[k+1])/dp[k]
    
x

array([0.19285714, 0.11428571, 0.175     , 0.09285714, 0.22678571])

In [84]:
np.linalg.solve(A,b)

array([0.19285714, 0.11428571, 0.175     , 0.09285714, 0.22678571])

In [86]:
L = np.eye(n)+np.diag(cp,k = -1)
U = np.diag(dp)+np.diag(e,k = 1)
L@U

array([[4., 2., 0., 0., 0.],
       [1., 4., 2., 0., 0.],
       [0., 1., 4., 2., 0.],
       [0., 0., 1., 4., 2.],
       [0., 0., 0., 1., 4.]])

In [153]:
n = 5
c = np.ones(n-1)
d = 2*np.ones(n)
e = np.ones(n-1)
b = np.ones(n)

A = np.diag(c,k=-1) + np.diag(d) + np.diag(e,k=1)
np.linalg.solve(A,b)

array([0.5, 0. , 0.5, 0. , 0.5])

In [154]:
#cc, dd, ee = LUdecomp3(c,d,e)
#LUsolve3(cc,dd,ee,b)

#L = np.eye(n) + np.diag(cc,k=-1)
#U = np.diag(dd)+ np.diag(ee,k=1)

In [155]:
AA = A.copy()
for k in range(0,n-1):
    for i in range(k+1,n):
        if AA[i,k] != 0:
            lam = AA[i,k]/AA[k,k]
            AA[i,k+1:n] = AA[i,k+1:n] - lam*AA[k,k+1:n]
            AA[i,k] = lam
print(AA)

x = np.zeros(n)
y = np.zeros(n)

for i in range(0,n):
    y[i] = b[i] - np.dot(AA[i,0:i],y[0:i])
for j in range(n-1,-1,-1):
    x[j] = (y[j] - np.dot(AA[j,j+1:n],x[j+1:n]))/AA[j,j]
x

[[2.         1.         0.         0.         0.        ]
 [0.5        1.5        1.         0.         0.        ]
 [0.         0.66666667 1.33333333 1.         0.        ]
 [0.         0.         0.75       1.25       1.        ]
 [0.         0.         0.         0.8        1.2       ]]


array([0.5, 0. , 0.5, 0. , 0.5])

In [156]:
for k in range(1,n):
    lam = c[k-1]/d[k-1]
    d[k] = d[k] - lam*e[k-1]
    c[k-1] = lam
L = np.diag(c,k=-1) +np.eye(n)
U = np.diag(d) + np.diag(e,k=1)
print(L+U-np.eye(n),'\n', L@U)

[[2.         1.         0.         0.         0.        ]
 [0.5        1.5        1.         0.         0.        ]
 [0.         0.66666667 1.33333333 1.         0.        ]
 [0.         0.         0.75       1.25       1.        ]
 [0.         0.         0.         0.8        1.2       ]] 
 [[2. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [0. 1. 2. 1. 0.]
 [0. 0. 1. 2. 1.]
 [0. 0. 0. 1. 2.]]


In [157]:
y = np.zeros(n)
x = np.zeros(n)

y[0] = b[0]
for k in range(1,n):
    y[k] = b[k] - c[k-1]*y[k-1]
x[n-1] = y[n-1]/d[n-1]
for k in range(n-2,-1,-1):
    x[k] = (y[k] - e[k]*x[k+1])/d[k]
    
x

array([0.5, 0. , 0.5, 0. , 0.5])

In [ ]:
c = np.array([-2,-6,12,-6],dtype = float)
d = np.array([2,5,16,39,14],dtype = float)