In [1]:
import numpy as np

In [2]:
A = np.array([[.6,-.4,1.],
              [-.3,.2,.5],
              [.6,-1.,.5]])
b = np.eye(3)

np.linalg.solve(A,b)

array([[ 1.66666667, -2.22222222, -1.11111111],
       [ 1.25      , -0.83333333, -1.66666667],
       [ 0.5       ,  1.        ,  0.        ]])

In [3]:
from ch2 import *

In [4]:
AA = A.copy()
LU, seq = LUdecompp(AA)
x0 = LUsolvee(LU,b[:,0],seq)
x1 = LUsolvee(LU,b[:,1],seq)
x2 = LUsolvee(LU,b[:,2],seq)

x = np.array([x0,x1,x2]).T
print(x)

[[ 1.66666667 -2.22222222 -1.11111111]
 [ 1.25       -0.83333333 -1.66666667]
 [ 0.5         1.          0.        ]]


In [5]:
A@x

array([[ 1.00000000e+00, -4.44089210e-16, -1.18423789e-16],
       [ 0.00000000e+00,  1.00000000e+00,  5.92118946e-17],
       [ 0.00000000e+00, -3.33066907e-16,  1.00000000e+00]])

In [6]:
def inverse(A):
    AA = A.copy()
    n = len(AA)
    LU, seq = LUdecompp(AA)
    x = np.zeros((n,n))

    for i in range(0,n):
        x[:,i] = LUsolvee(LU,b[:,i],seq)
    return x

In [7]:
n = 6
c = - np.ones(n-1)
d = 2*np.ones(n)
e = - np.ones(n-1)
d[n-1] = 5

In [8]:
cc,dd,ee = c.copy(),d.copy(),e.copy()
x = np.zeros((n,n))
b = np.eye(n)
LUdecomp3(cc,dd,ee)
for i in range(0,n):
    x[:,i] = LUsolve3(cc,dd,ee,b[:,i])
print(x)


[[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


In [9]:
A = np.diag(c,k=-1) +np.diag(d)+np.diag(e,k=1)
A@x

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16,  1.00000000e+00, -2.22044605e-16,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.66533454e-16, -3.33066907e-16,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00, -1.11022302e-16,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.93889390e-18, -1.38777878e-17,  1.11022302e-16,
         1.38777878e-16,  1.00000000e+00,  2.77555756e-17],
       [-2.08166817e-17, -4.16333634e-17,  0.00000000e+00,
        -2.77555756e-17, -8.32667268e-17,  1.00000000e+00]])

In [10]:
A = np.array([[4,-1,1],[-1,4,-2],[1,-2,4]],dtype = float)
b = np.array([12,-1,5])
x = np.zeros(3)
w = 1

n = len(A)
for j in range(0,12,1):
    for i in range(0,n):
        x[i] = w/A[i,i]*(b[i] - (np.dot(A[i,0:i],x[0:i])+np.dot(A[i,i+1:n],x[i+1:n]))) + (1-w)*x[i]


x

array([3., 1., 1.])

In [11]:
A = np.array([[3,-3,3],[-3,5,1],[3,1,5]],dtype = float)
b = np.array([9,-7,12])

n = len(A)
x = np.array([3.5,2/3,1/6],dtype = float)
w = 1
for j in range(0,30,1):
    for i in range(0,n):
        x[i] = w/A[i,i]*(b[i] - (np.dot(A[i,:],x[:])-A[i,i]*x[i])) + (1-w)*x[i]
x #diverge!

array([3.5       , 0.66666667, 0.16666667])

In [12]:
A = np.array([[4,-1,1],[-1,4,-2],[1,-2,4]],dtype = float)
b = np.array([12,-1,5])

n = len(A)
x0 = np.zeros(3)

In [13]:
# First iteratiion
r0 = b - A@x0  # Residual, 차이
s0 = r0.copy() # search direction
a0 = r0@s0/(s0@A@s0)

# update x
x1 = x0 + a0*s0
print(x1)

# Second iteration
r1 = b - A@x1  # new Residual, 차이
b0 = - r1@A@s0/(s0@A@s0) # 새로운 탐색방향을 찾는 계수
s1 = r1 + b0*s0 # new search direction
a1 = r1@s1/(s1@A@s1)
x2 = x1 + a1*s1
print(x2)

# Third iteration
r2 = b - A@x2  # Residual, 차이
b1 = - r2@A@s1/(s1@A@s1) # 새로운 탐색방향을 찾는 계수
s2 = r2 + b1*s1 # new search direction
a2 = r2@s2/(s2@A@s2)
x3 = x2 + a2*s2
print(x3)

[ 2.41706161 -0.2014218   1.007109  ]
[3.07752283 0.79483181 0.71998218]
[3. 1. 1.]


In [14]:
A = np.array([[3,-3,3],[-3,5,1],[3,1,5]],dtype = float)
b = np.array([9,-7,12])

n = len(A)
x0 = np.zeros(n)

In [15]:
# First iteratiion
r0 = b - A@x0  # Residual, 차이
s0 = r0.copy() # search direction
a0 = r0@s0/(s0@A@s0)

# update x
x1 = x0 + a0*s0
print(x1)

# Second iteration
r1 = b - A@x1  # new Residual, 차이
b0 = - r1@A@s0/(s0@A@s0) # 새로운 탐색방향을 찾는 계수
s1 = r1 + b0*s0 # new search direction
a1 = r1@s1/(s1@A@s1)
x2 = x1 + a1*s1
print(x2)

# Third iteration
r2 = b - A@x2  # Residual, 차이
b1 = - r2@A@s1/(s1@A@s1) # 새로운 탐색방향을 찾는 계수
s2 = r2 + b1*s1 # new search direction
a2 = r2@s2/(s2@A@s2)
x3 = x2 + a2*s2
print(x3)

[ 1.19361084 -0.92836399  1.59148112]
[ 18.34439265   3.8788959  -13.41230235]
[3.5        0.66666667 0.16666667]


In [25]:
tol = 1.0e-15
x = np.ones(n)
r = b - A@x
s = r.copy()
for i in range(n):
    alpha = r@s/(s@A@s)
    x = x + alpha*s
    r = b - A@x
    if np.sqrt(np.dot(r,r)) < tol:
        break
    else:
        beta = - r@A@s/(s@A@s)
        s = r + beta*s

x, i

(array([3.5       , 0.66666667, 0.16666667]), 2)

In [22]:
Av = lambda x: A@x

x = np.zeros(3)
conjGrad(Av,x,b)

(array([3.5       , 0.66666667, 0.16666667]), 2)