In [1]:
import numpy as np

In [2]:
#1

AA = np.array([[  1.,  2.,  4.],
              [  3.,  8., 14.],
              [  2.,  6., 13.]])
bb = np.array([ 3., 13., 4.])

A = AA.copy()
b = bb.copy()

lam01 = A[1,0]/A[0,0]
A[1,:] = A[1,:] - lam01*A[0,:]
b[1]   = b[1]   - lam01*b[0]

lam02 = A[2,0]/A[0,0]
A[2,:] = A[2,:] - lam02*A[0,:]
b[2]   = b[2]   - lam02*b[0]

lam12 = A[2,1]/A[1,1]
A[2,:] = A[2,:] - lam12*A[1,:]
b[2]   = b[2]   - lam12*b[1]

print(A,'\n')

n = len(b)
x = np.zeros(n)

x[2] =  b[2]/A[2,2]
x[1] = (b[1] - np.dot(A[1,2:n],x[2:n]))/A[1,1]
x[0] = (b[0] - np.dot(A[0,1:n],x[1:n]))/A[0,0]

print('x = ',x)

[[1. 2. 4.]
 [0. 2. 2.]
 [0. 0. 3.]] 

x =  [ 3.  4. -2.]


In [3]:
np.linalg.solve(AA,bb)

array([ 3.,  4., -2.])

In [4]:
#2

AA = np.array([[  0.,  0.,  2.,  1.,  2.],
               [  0.,  1.,  0.,  2., -1.],
               [  1.,  2.,  0., -2.,  0.],
               [  0.,  0.,  0., -1.,  1.],
               [  0.,  1., -1.,  1., -1.]])
bb = np.array([  1.,  1., -4., -2., -1.])

A = AA.copy()
b = bb.copy()

A[0,:] = AA[2,:]
b[0]   = bb[2]
A[2,:] = AA[0,:]
b[2]   = bb[0]

lam01 = A[1,0]/A[0,0]
A[1,:] = A[1,:] - lam01*A[0,:]
b[1]   = b[1]   - lam01*b[0]

lam02 = A[2,0]/A[0,0]
A[2,:] = A[2,:] - lam02*A[0,:]
b[2]   = b[2]   - lam02*b[0]

lam03 = A[3,0]/A[0,0]
A[3,:] = A[3,:] - lam03*A[0,:]
b[3]   = b[3]   - lam03*b[0]

lam04 = A[4,0]/A[0,0]
A[4,:] = A[4,:] - lam04*A[0,:]
b[4]   = b[4]   - lam04*b[0]

lam12 = A[2,1]/A[1,1]
A[2,:] = A[2,:] - lam12*A[1,:]
b[2]   = b[2]   - lam12*b[1]

lam13 = A[3,1]/A[1,1]
A[3,:] = A[3,:] - lam13*A[1,:]
b[3]   = b[3]   - lam13*b[1]

lam14 = A[4,1]/A[1,1]
A[4,:] = A[4,:] - lam14*A[1,:]
b[4]   = b[4]   - lam14*b[1]

lam23 = A[3,2]/A[2,2]
A[3,:] = A[3,:] - lam23*A[2,:]
b[3]   = b[3]   - lam23*b[2]

lam24 = A[4,2]/A[2,2]
A[4,:] = A[4,:] - lam24*A[2,:]
b[4]   = b[4]   - lam24*b[2]

lam34 = A[4,3]/A[3,3]
A[4,:] = A[4,:] - lam34*A[3,:]
b[4]   = b[4]   - lam34*b[3]

print(A,'\n')

n = len(b)
x = np.zeros(n)

x[4] =  b[4]/A[4,4]
x[3] = (b[3] - np.dot(A[3,4:n],x[4:n]))/A[3,3]
x[2] = (b[2] - np.dot(A[2,3:n],x[3:n]))/A[2,2]
x[1] = (b[1] - np.dot(A[1,2:n],x[2:n]))/A[1,1]
x[0] = (b[0] - np.dot(A[0,1:n],x[1:n]))/A[0,0]

print('x = ',x)

[[ 1.   2.   0.  -2.   0. ]
 [ 0.   1.   0.   2.  -1. ]
 [ 0.   0.   2.   1.   2. ]
 [ 0.   0.   0.  -1.   1. ]
 [ 0.   0.   0.   0.   0.5]] 

x =  [ 2. -2.  1.  1. -1.]


In [5]:
np.linalg.solve(AA,bb)

array([ 2., -2.,  1.,  1., -1.])

In [6]:
#3

# Lower triangular
def gaussL(aa,bb):
    a = aa.copy()
    b = bb.copy()
    n = len(a)
    for k in range(n-1,0,-1):
        for i in range(k-1,-1,-1):
            if a[i,k] != 0.:
                lam = a[i,k]/a[k,k]
                a[i,0:k] = a[i,0:k] - lam*a[k,0:k]
                b[i]     = b[i]     - lam*b[k]
    for j in range(0,n,1):
        b[j] = (b[j] - np.dot(a[j,0:j],b[0:j]))/a[j,j]
    return b

# Upper triangular
def gauss(aa,bb):
    # Elimination phase
    a = aa.copy()
    b = bb.copy()
    n = len(a)
    x = np.zeros(n)
    for k in range(0,n-1): # pivot rows k = 0, 1, ...
        for i in range(k+1,n): # range i = 1
            if a[i,k] != 0.0 :
            # print('We are in the loop',i,k)
                lam = a[i,k]/a[k,k] # Definion of lambda
                a[i,k:n] = a[i,k:n] - lam*a[k,k:n] # a[i,k+1:n] 까지 변경
                b[i] = b[i] - lam*b[k]
    # Back substitution
    for k in range(n-1,-1,-1): # From end to beginning
        x[k] = ( b[k] - np.dot(a[k,k+1:n],x[k+1:n]) )/a[k,k] # j = k+1, ..., n
    return x

In [7]:
A = np.random.rand(4,5)
a = A[0:4,0:4]
b = A[:,4]

print('',gaussL(a,b),'\n',gauss(a,b))

 [ 0.78398048 -0.20777324  3.75004812 -3.5919258 ] 
 [ 0.78398048 -0.20777324  3.75004812 -3.5919258 ]


In [8]:
#4

def LUsolve(aa,bb):
    a = aa.copy()
    b = bb.copy()
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.:
                lam = a[i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    for k in range(0,n,1):
        b[k] =  b[k] - np.dot(a[k,0:k],b[0:k])
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b


In [9]:
A = np.random.rand(3,4)
a = A[0:3,0:3]
b = A[:,3]

print('',LUsolve(a,b),'\n',np.linalg.solve(a,b))

 [ -6.13498134 -11.35189313  13.47089499] 
 [ -6.13498134 -11.35189313  13.47089499]


In [10]:
#5

g     =  10. #m/s/s
theta =  40.*(np.pi/180)
m     =  [10., 4., 5., 6.]
u     =  [0.25, 0.3, 0.2]

# [ T1, T2, T3, a]

A = np.array([[  1.,  0.,  0., m[0]],
              [ -1.,  1.,  0., m[1]],
              [  0., -1.,  1., m[2]],
              [  0.,  0., -1., m[3]]])
b = np.array([ m[0]*g*(np.sin(theta)-u[0]*np.cos(theta)),
               m[1]*g*(np.sin(theta)-u[1]*np.cos(theta)),
               m[2]*g*(np.sin(theta)-u[2]*np.cos(theta)),
              -m[3]*g                                   ])

print('[ T1, T2, T3, a] = ',LUsolve(A,b))

[ T1, T2, T3, a] =  [34.67742709 47.01630903 66.27013368  1.04502228]
